#!/bin/bash
# double durations!!

sed -e 's/\([a-z][a-z]*\)32/\164/g' \
-e 's/\([a-z][a-z]*\)16/\132/g' \
-e 's/\([a-z][a-z]*\)8/\116/g' \
-e 's/\([a-z][a-z]*\)4/\18/g' \
-e 's/\([a-z][a-z]*\)2/\14/g' \
-e  's/\([a-z][a-z]*\)1/\12/g' 

