#!/bin/bash
PROCESS=kwm
number=$(ps aux | grep $PROCESS | wc -l)

if [ $number -gt 1 ]
    then
	    tmux send-keys -t kwm 'kwm' C-m
    else
	    tmux new -s kwm -d
	    tmux send-keys -t kwm 'kwm' C-m
fi

